---
# yamllint disable rule:line-length
name: Backend CI
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: backend

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - lint
          - docstrings-coverage
          - isort
          - format
          - typing
          - security
          - tests
    name: ${{ matrix.job }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install --no-cache-dir --upgrade pip tox tox-uv

      - name: Run ${{ matrix.job }}
        run: tox -e ${{ matrix.job }}

  coverage:
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install --no-cache-dir --upgrade pip tox tox-uv

      - name: Run coverage
        run: tox -e coverage

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@50d15ff8768f6d897b04e5a0805bd1a98f7096c4  # v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MAX_FILES_IN_COMMENT: 120
          COVERAGE_PATH: backend

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
