---
# yamllint disable rule:line-length
name: Report Frontend Coverage

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed

defaults:
  run:
    working-directory: frontend

jobs:
  report:
    name: Report coverage
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
      # Gives the action the necessary permissions for looking up the
      # workflow that launched this workflow, and download the related
      # artifact that contains the comment to be published
      actions: read

    steps:
      # DO NOT run actions/checkout here, for security reasons
      # For details, refer to https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
      - uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: Frontend
