---
# yamllint disable rule:line-length
name: Report Frontend Coverage

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed

defaults:
  run:
    working-directory: frontend

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      # - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: Frontend
          vite-config-path: frontend/vite.config.js
