---
# yamllint disable rule:line-length
name: Frontend CI
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Run tests and generate coverage
        # run: npx vitest --coverage.enabled true
        run: npm run test

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: frontend/coverage
