---
# yamllint disable rule:line-length
name: Pre-commit
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: "24.x"

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Install backend dependencies
        working-directory: backend
        run: pip install --no-cache-dir --upgrade pip tox tox-uv

      - name: Run pre-commit
        working-directory: backend
        run: tox -e pre-commit
